--- 
git:
  url: "https://github.com/GauravGirase/springBootAppDemo.git"
  branch: "main"
  credentials: "gitCredentials"

docker:
  port: "9001"
  dockerfile: .
  dockerCredentials: "dockerhubcredentials"
  
ssh:
  host_ip: "172.31.34.100"
  host_user: "ec2-user"
  
  
  
  
